---
apiVersion: extensions/v1beta2
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: weather
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: adilog/weather:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: webserver
          protocol: TCP
