---
- name: Create kubernetes script directory
  file: path={{ kube_script_dir }} state=directory

- name: Create system kube-cert groups
  group: name={{ kube_cert_group }} state=present system=yes

- name: Create system kube user
  user:
    name=kube
    comment="Kubernetes user"
    shell=/sbin/nologin
    state=present
    system=yes
    groups={{ kube_cert_group }}


- name: Read back the kubecfg key
  slurp:
    src: "{{ kube_cert_dir }}/kubecfg.key"
  register: api_key
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Register the cfg key as a fact so it can be used later
  set_fact:
    kube_api_key: "{{ api_key.content|b64decode }}"